### ISSUE TITLE
How can I get the token?

### ISSUE THREAD

**Issue by asifrafeeq** [aksafan/yii2-fcm-both-api#1]
I want to send the and receive the Push notification, I am using an actionPushnotification for this.
but I am getting an error 
```
PHP Notice – yii\base\ErrorException
Undefined variable: fcm
```
my configurations are 
```
  'fcm' => [
            'class' => 'aksafan\fcm\source\components\Fcm',
            'apiVersion' => \aksafan\fcm\source\requests\StaticRequestFactory::API_V1,
            'apiParams' => [
                'privateKey' => '@web/privateKeyFile.json',
            ],
       ]
```

in controller I am implementing the code as follow
```
public function actionPushnotifications()
            {
        
                $result = $fcm
                ->createRequest()
                ->setTarget(MessageOptionsBuilder::TOKEN, $token)
                ->setData(['a' => '1', 'b' => 'test'])
                ->setNotification('Test Title', 'Test Description')
                ->send();
                
            if ($result->isResultOk()) {
                echo $result->getRawMessageId();
                echo $result->getMessageId();
            } else {
                $tokensToDelete = $result->getTokensToDelete();
                $errorDetails = $result->getErrorDetails();
                echo $result->getErrorStatusDescription();
            }

        }
```
please guide me and help me .. thanks a lot in advance :)

**Comment by aksafan** [comment]
@asifrafeeq hello!

In order to use [Yii2 components](https://github.com/yiisoft/yii2/blob/master/docs/guide/structure-application-components.md#application-components), you need to register it in config file (as you did correctly) and then you can access an application component through the expression:
`\Yii::$app->componentID`

So change your code to:
 $result = Yii::$app
                 ->fcm
                ->createRequest()
                ->setTarget(MessageOptionsBuilder::TOKEN, $token)
                ->setData(['a' => '1', 'b' => 'test'])
                ->setNotification('Test Title', 'Test Description')
                ->send();
and you are OK.
