### ISSUE TITLE
Enable/disable notifications from config file

### ISSUE THREAD

**Issue by tsvetiligo** [aksafan/yii2-fcm-both-api#2]
Is there a way to enable/disable notifications from config file for dev?

**Comment by aksafan** [comment]
Hello @tsvetiligo 

For now no. I handle env difference before using this library in my projects, but this is good point to improve. Will add it to my plan, Thank you for thougts.

**Comment by aksafan** [comment]
Hey @tsvetiligo  What behavior do you expect when notifications is disabled?

**Comment by aksafan** [comment]
Closing this issue as no answer for 3 years.
