### ISSUE TITLE
Use HTTP v1 and Legacy API at same time.

### ISSUE THREAD

**Issue by AmbrocioIsaias2808** [aksafan/yii2-fcm-both-api#3]
Hi, it is posible to configure both HTTP v1 and legacy API to use them at the same time? The thing is that i wolud like to use HTTP v1 but legacy has the feature to send specific push messages to a list of tokens and it would come in handy on what i´m doing.

**Comment by AmbrocioIsaias2808** [comment]
As no one has respond i will answer my own question. Maybe is something basic but i´m technically new in Yii2, and well i think this should be in the main documentation of this extension.

Any way, to use them at the same time 

![image](https://user-images.githubusercontent.com/44043979/87879881-eb769400-c9b2-11ea-88f2-706cba380cc7.png)


Once setup every value in the configuration, on a controller action or anywhere you want you can indicate the framework that the next instructions will be made with a different API like this.

`
 $tokens = ["Token 1","Token 2","Token 3"];
        
        /*As our main configuration is set to use HTTP v1 we need to indicate that the next instructions will be processed in Legacy, 
           to do that we do: */
        Yii::$app->fcm->apiVersion=\aksafan\fcm\source\requests\StaticRequestFactory::LEGACY_API;

        $result = Yii::$app
            ->fcm
            ->createRequest()
            ->setTarget(\aksafan\fcm\source\builders\legacyApi\MessageOptionsBuilder::TOKENS, $tokens)->setNotification('Test API', 'Description API')
            ->send();
        return $this->render('index',["result"=>$result]);
    }
`
This way you can send push notifications with Legacy API even if your main configuration is for using HTTP v1.

Well, thats how i figured out, maybe there is a simpler or cleaner way of doing this so i´m open for suggestions.

PD: @aksafan thanks for this extension, it helps me a lot with i´m doing. Also are you ok? I check your profile and didn´t seen activity from 2 years ago.

**Comment by aksafan** [comment]
Hello @AmbrocioIsaias2808 

Thank you for interesting in my library and excuse me for long answer - was a bit busy with a new job.

As for your question, the most efficient way to use both variants is to register them separately:
```
return [
    //....
    'components' => [
        'fcmApiV1' => [
            'class' => 'aksafan\fcm\source\components\Fcm',
            'apiVersion' => \aksafan\fcm\source\requests\StaticRequestFactory::API_V1,
            'apiParams' => [
                'privateKey' => '/path/to/your/file/privateKeyFile.json',
            ],
        ],
        'fcmLegacyApi' => [
            'class' => 'aksafan\fcm\source\components\Fcm',
            'apiVersion' => \aksafan\fcm\source\requests\StaticRequestFactory::LEGACY_API,
            'apiParams' => [
                'serverKey' => 'aef',
                'senderId' => 'fwef',
            ],
        ],
    ]
];
```
Now you can use `Yii::$app->fcmApiV1` when need APIV1 and `Yii::$app->fcmLegacyApi` for legacy one.

Your variant will also work but will be not so clear and you change the state of singletone object during runtime.

Updated Readme in the latest release - https://github.com/aksafan/yii2-fcm-both-api/releases/tag/0.9.4


> PD: @aksafan thanks for this extension, it helps me a lot with i´m doing. Also are you ok? I check your profile and didn´t seen activity from 2 years ago.

You are welcome! Glad to hear it helps you =)
I'm pretty OK, just had a bunch of work on a new job (several month).
As for activity, I released a composer [plugin](https://github.com/aksafan/composer-changelog) for easy and clear upgrade notes and I'm in preparation of huge library for safe working with RabbitMQ (hope to release it soon).

Best regards,
Aksafan
