### ISSUE TITLE
StaticBuilderFactory FOR_TOPIC_SENDING failure

### ISSUE THREAD

**Issue by berrytechnics** [aksafan/yii2-fcm-both-api#8]
Im not sure what could be causing this. I am able to push to tokens without issue, and able to push tests to topics from FCM Console without issue. 

```
<pre>Exception 'InvalidArgumentException' with message 'reason param must be in [for_token_sending, for_topic_sending, for_group_sending, for_topic_management].' 

in /var/www/html/online/vendor/aksafan/yii2-fcm-both-api/source/builders/StaticBuilderFactory.php:61

Stack trace:
#0 /var/www/html/online/vendor/aksafan/yii2-fcm-both-api/source/requests/ApiV1Request.php(48): aksafan\fcm\source\builders\StaticBuilderFactory::build('for_topic_sendi...', Object(aksafan\fcm\source\requests\ApiV1Request))
#1 /var/www/html/online/vendor/aksafan/yii2-fcm-both-api/source/requests/StaticRequestFactory.php(41): aksafan\fcm\source\requests\ApiV1Request-&gt;__construct(Array, 'for_topic_sendi...')
#2 /var/www/html/online/vendor/aksafan/yii2-fcm-both-api/source/components/Fcm.php(40): aksafan\fcm\source\requests\StaticRequestFactory::build('api_v1', Array, 'for_topic_sendi...')
#3 /var/www/html/online/frontend/controllers/FcmController.php(56): aksafan\fcm\source\components\Fcm-&gt;createRequest('for_topic_sendi...')
#4 [internal function]: frontend\controllers\FcmController-&gt;actionPushTopicTest()
#5 /var/www/html/online/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/html/online/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction-&gt;runWithParams(Array)
#7 /var/www/html/online/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller-&gt;runAction('push-topic-test', Array)
#8 /var/www/html/online/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module-&gt;runAction('fcm/push-topic-...', Array)
#9 /var/www/html/online/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application-&gt;handleRequest(Object(yii\web\Request))
#10 /var/www/html/online/frontend/web/index.php(22): yii\base\Application-&gt;run()
#11 {main}</pre>
```

My method (direct from example)

```
public function actionPushTopicTest(){
        $result = Yii::$app->fcm 
            ->createRequest(\aksafan\fcm\source\builders\StaticBuilderFactory::FOR_TOPIC_SENDING)
            ->setTarget(\aksafan\fcm\source\builders\legacyApi\MessageOptionsBuilder::TOPIC, 'frontend')
            ->setNotification('Test title', 'Test description')
            ->send();

        if ($result->isResultOk()) {
            return $result->getMessageId();
        } else {
            return $result->getErrorStatusDescription();
        }
    }
```

**Comment by bc-anton-k** [comment]
Hey @berrytechnics, 

Thank you for rising this question.

From this trace
> #2 /var/www/html/online/vendor/aksafan/yii2-fcm-both-api/source/components/Fcm.php(40): aksafan\fcm\source\requests\StaticRequestFactory::build('api_v1', Array, 'for_topic_sendi...')
 
I see that you use `api_v1` in your config file.

But in your `actionPushTopicTest` method you use `legacyApi`, so to fix the problem you need to choose the one path and either change version in config or in your target method.

**Comment by aksafan** [comment]
Hey @berrytechnics, 

Thank you for rising this question.

From this trace
> 2 /var/www/html/online/vendor/aksafan/yii2-fcm-both-api/source/components/Fcm.php(40): aksafan\fcm\source\requests\StaticRequestFactory::build('api_v1', Array, 'for_topic_sendi...')
 
I see that you use `api_v1` in your config file.

But in your `actionPushTopicTest` method you use `legacyApi`, so to fix the problem you need to choose the one path and either change version in config or in your target method.

**Comment by berrytechnics** [comment]
You are exactly correct! I had configured my app for the v1 api, but was calling legacy methods. Thank you for taking the time to help, i was pulling hair out over a simple issue...
Turns out everything i want to do is within the legacy api anyway!

**Comment by bc-anton-k** [comment]
> You are exactly correct! I had configured my app for the v1 api, but was calling legacy methods. Thank you for taking the time to help, i was pulling hair out over a simple issue... Turns out everything i want to do is within the legacy api anyway!

Glad to help!
