### ISSUE TITLE
Android channel id

### ISSUE THREAD

**Issue by LLouzada** [aksafan/yii2-fcm-both-api#9]
Is it possible to set the channel id for android? I tried adding "android_channel_id" to setAndroidConfig, 
'notification' => [
                        'title' => $title,
                        'body' => $message,
                        'android_channel_id' => $type,
                    ],
But this seems not to work.

**Comment by bc-anton-k** [comment]
Hello @LLouzada1,

Thank you for asking!

You can add any [Android specific keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) for notification messages, as well as `android_channel_id`. Just pass array of configs to `setAndroidConfig()` method with `android_channel_id` key-value under `notification` section (see example below).

```php
/** @var \aksafan\fcm\source\responses\apiV1\TokenResponse $result */
$result = Yii::$app
    ->fcm
    ->createRequest()
    ->setTarget(\aksafan\fcm\source\builders\apiV1\MessageOptionsBuilder::TOKEN, 'your_token')
    ->setAndroidConfig([
        'ttl' => '3600s',
        'priority' => 'normal',
        'notification' => [
            'title' => 'Android Title',
            'body' => 'Android Description.',
            'icon' => 'stock_ticker_update',
            'color' => '#ff0000',
            'android_channel_id' => '123456',
        ],
    ])
    ->send();
```

Make sure to create a channel with this channel ID before any notification with this channel ID is received. 
Ref to official [documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) (Table 2b. Android — keys for notification messages):
<img width="903" alt="image" src="https://user-images.githubusercontent.com/88430055/220489138-355061af-a380-47bc-87ab-bf5d99dbf762.png">

**Comment by LLouzada** [comment]
Hi @bc-anton-k , thank you for your reply!

Me and my team managed to make it work using the key channel_id, not android_channel_id, as mentined in here https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification.

But I guess the way you showed should work too, anyway, thank you for your time :)
